jtype: ExecutorSimpleFileServer
py_modules:
  - executor.py
metas:
  name: ExecutorSimpleFileServer
  description:
  url: https://github.com/themantalope/executor-simple-file-server
  keywords: [docker, docker-compose, executor, file server]
