version: "3.7"
services:
  simple-file-server:
    image: flaviostutz/simple-file-server:latest
    ports:
      - "4000:4000"
    environment:
      - WRITE_SHARED_KEY=
      - READ_SHARED_KEY=
      - LOCATION_BASE_URL=http://localhost:4000
      - LOG_LEVEL=debug
